# ==========================================================
# email_sender.py — Email Notification Module (Fake Detection)
# ==========================================================
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_RECIPIENTS


def create_email_body(summary: dict) -> str:
    """Create HTML email body from fake detection summary."""
    
    timestamp = summary.get("sync_timestamp", "N/A")
    total_processed = summary.get("total_records_processed", 0)
    flagged_count = summary.get("flagged_entities", 0)
    fp_pct = summary.get("false_positive_percentage", "0%")
    execution_time = summary.get("execution_time_seconds", 0)

    # Determine status color
    if flagged_count > 0:
        status_color = "#e67e22"  # Orange for "Review Required"
        status_text = "⚠️ Review Required"
    else:
        status_color = "#27ae60"  # Green
        status_text = "✅ No Fake Products Detected"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #2c3e50 0%, #000000 100%); 
                       color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }}
            .content {{ background: #ffffff; padding: 25px; border: 1px solid #e1e1e1; }}
            .stat-container {{ display: flex; flex-wrap: wrap; justify-content: center; margin-top: 15px; }}
            .stat-box {{ background: #f8f9fa; padding: 15px; margin: 5px; border-radius: 8px; 
                         border: 1px solid #eee; min-width: 120px; text-align: center; }}
            .stat-value {{ font-size: 20px; font-weight: bold; color: #2c3e50; }}
            .stat-label {{ font-size: 11px; color: #7f8c8d; text-transform: uppercase; letter-spacing: 1px; }}
            .status {{ background: {status_color}; color: white; padding: 8px 16px; 
                       border-radius: 20px; display: inline-block; margin: 15px 0; font-weight: bold; }}
            .footer {{ background: #f8f9fa; color: #95a5a6; padding: 15px; font-size: 11px; 
                       border-radius: 0 0 8px 8px; text-align: center; border: 1px solid #e1e1e1; border-top: none; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1 style="margin:0; font-size: 24px;">🚫 Fake Product Detection</h1>
                <p style="margin:5px 0 0 0; opacity:0.8;">Automated Pipeline Summary</p>
            </div>
            <div class="content">
                <p><strong>Sync Timestamp:</strong> {timestamp}</p>
                
                <div style="text-align: center;">
                    <div class="status">{status_text}</div>
                </div>
                
                <h3 style="border-bottom: 2px solid #eee; padding-bottom: 8px; color: #2c3e50;">📊 pipeline Statistics</h3>
                <div class="stat-container">
                    <div class="stat-box">
                        <div class="stat-value">{total_processed}</div>
                        <div class="stat-label">Total Scanned</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value" style="color: {status_color};">{flagged_count}</div>
                        <div class="stat-label">Flagged Fakes</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{fp_pct}</div>
                        <div class="stat-label">Flag Rate</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{execution_time}s</div>
                        <div class="stat-label">Exec Time</div>
                    </div>
                </div>
                
                {"<p style='margin-top:20px; background: #fff3e0; padding: 10px; border-left: 4px solid #ff9800;'><strong>📎 Attachment:</strong> A detailed CSV report of flagged items is attached for your review.</p>" if flagged_count > 0 else ""}
            </div>
            <div class="footer">
                Generated by Counterfeit Detection Engine • {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
            </div>
        </div>
    </body>
    </html>
    """
    return html


def send_moderation_report_email(
    summary: dict,
    csv_path: str = None,
    recipients: list = None,
    subject: str = None
) -> dict:
    """
    Send moderation report email with optional CSV attachment.
    """
    
    # Validate config
    if not SMTP_USER or not SMTP_PASSWORD:
        return {
            "success": False,
            "message": "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD env vars."
        }
    
    # Use provided recipients or fall back to config
    if recipients is None:
        recipients = EMAIL_RECIPIENTS
    
    if not recipients:
        return {
            "success": False,
            "message": "No email recipients configured. Set EMAIL_RECIPIENTS env var."
        }
    
    # Generate subject if not provided
    if subject is None:
        flagged = summary.get("flagged_entities", 0)
        if flagged > 0:
            subject = f"🚨 ALERT: {flagged} Suspected Fake Products Detected"
        else:
            subject = "✅ Fake Detection Report: No Threats Found"
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg["From"] = SMTP_USER
        msg["To"] = ", ".join(recipients)
        msg["Subject"] = subject
        
        # Attach HTML body
        html_body = create_email_body(summary)
        msg.attach(MIMEText(html_body, "html"))
        
        # Attach CSV if provided and file exists
        if csv_path and os.path.exists(csv_path):
            with open(csv_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                
                filename = os.path.basename(csv_path)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={filename}"
                )
                msg.attach(part)
        
        # Send email
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipients, msg.as_string())
        
        return {
            "success": True,
            "message": f"Email sent successfully to {len(recipients)} recipient(s)",
            "recipients": recipients
        }
    
    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "message": "SMTP authentication failed. Check credentials."
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Failed to send email: {str(e)}"
        }
